--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fv-dg/Tardis
build-by-default: true
branches:
- master
projects:
  Tardis:
    path: ""
    libs:
      - src: "ParoxityTeam/Commando/Commando"
        version: ^2.1.0

  lint:
    phpstan: false
...
