### Tardis config
### DO NOT CHANGE CONFIG VERSION
config-version: 1

### load all levels on server start [true:false]
### if false, levels can be renamed to their foldername via onLevelLoad
### or by command - /tr load <level>
loadall-on-startup: true